---
platform: linux

image_resource:
  type: docker-image
  source: {repository: starkandwayne/concourse}

inputs:  
- name: resource-gist
- name: first-pipeline

outputs:  
- name: updated-gist

run:
  path: first-pipeline/tasks/update-resource.sh
  