---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

inputs:  
- name: first-pipeline
- name: somefiles

run:
  path: first-pipeline/tasks/writefile.sh
  args: somefiles
  