---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/BasLaravel/test-pipeline.git
    branch: master

jobs:
- name: job-hello-world
  public: true
  plan:
  - get: resource-tutorial
  - task: task_1
    file: resource-tutorial/tasks/task_1.yml
