---
resources:
- name: first-pipeline
  type: git
  source:
    uri: https://github.com/BasLaravel/test-pipeline.git
    branch: master

jobs:
- name: job-hello-world
  public: true
  plan:
  - get: first-pipeline
  - task: hello-world
    file: first-pipeline/tasks/task_1.yml
